name: 同步Fork仓库（保护本地文件）

on:
  schedule:
    # 每周日凌晨执行
    - cron: '0 2 * * 0'
  workflow_dispatch:
    # 手动触发
    inputs:
      force_sync:
        description: '强制同步（忽略冲突）'
        required: false
        default: 'false'
        type: boolean

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出仓库
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: 同步上游仓库
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        # 上游仓库配置
        upstream_sync_repo: chendi0207/my-TVBOX
        upstream_sync_branch: main
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        test_mode: false
        
    - name: 保护本地仓.txt文件
      if: always()
      run: |
        # 检查是否存在本地仓.txt文件
        if [ -f "本地仓.txt" ]; then
          echo "检测到本地仓.txt文件"
          
          # 检查文件是否被修改
          if git status --porcelain | grep "本地仓.txt"; then
            echo "本地仓.txt文件有变更，恢复为本地版本"
            git checkout HEAD~1 -- "本地仓.txt" || echo "无法恢复，保持当前状态"
            git add "本地仓.txt"
            git commit -m "保护本地仓.txt文件不被上游覆盖" || echo "无需提交"
          else
            echo "本地仓.txt文件无变更"
          fi
        else
          echo "未找到本地仓.txt文件"
        fi
        
    - name: 推送保护后的更改
      if: always()
      run: |
        if git status --porcelain; then
          git push origin main
          echo "已推送保护本地文件后的更改"
        else
          echo "无需推送更改"
        fi